### ISSUE TITLE
plz fix

### ISSUE THREAD

**Issue by evilfactory** [ThePuzzler/GLua-Script#2]
7: attempt to call field 'Create' (a nil value)

**Comment by ThePuzzler** [comment]
naum tem "Create" >:(

**Comment by ThePuzzler** [comment]
é

**Comment by evilfactory** [comment]
TEM SIM PORA

**Comment by ThePuzzler** [comment]
NÃO TEM NA LINHA 7

**Comment by evilfactory** [comment]
DEU UNLOCK NE NA LINHA 7 * 3 TEM ERRO LA SEU ZUNV

**Comment by ThePuzzler** [comment]
NA LINHA 21 AINDA N EM ERRO

**Comment by evilfactory** [comment]
SE NÃO SABE MATEMATICA 7 * 3 E OUTRA COISA

**Comment by ThePuzzler** [comment]
QUER SABER
VO TE PROVAR ERRADO

**Comment by evilfactory** [comment]
[ERROR] Evil Factory:63: attempt to call global 'losebutton' (a nil value)
stack traceback:
	Evil Factory:63: in main chunk
	[C]: in function 'LUADEV_EXECUTE_FUNCTION'
Evil Factory:63: attempt to call global 'losebutton' (a nil value)

**Comment by ThePuzzler** [comment]
ITS BAD ERRORS

**Comment by evilfactory** [comment]
YOU ARE BAD CODER

**Comment by ThePuzzler** [comment]
A LINHA 63 É NULL

**Comment by evilfactory** [comment]
SHH LINHA 63 NÃO E NULL E
